# Generated by Django 5.0.3 on 2024-03-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReportContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.TextField(blank=True, null=True)),
                ('input_time', models.DateTimeField(auto_now_add=True, verbose_name='输入时间')),
            ],
            options={
                'verbose_name': '报告内容',
                'verbose_name_plural': '报告内容',
                'db_table': 'content',
            },
        ),
    ]
