# Generated by Django 5.0.3 on 2024-03-20 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportcontent',
            name='request_type',
            field=models.CharField(default='E', max_length=1, verbose_name='请求类型'),
        ),
    ]
