# Generated by Django 5.0.3 on 2024-03-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluate', '0002_reportcontent_request_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespondContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responds', models.TextField(blank=True, null=True)),
                ('request_type', models.CharField(default='E', max_length=1, verbose_name='请求类型')),
                ('output_time', models.DateTimeField(auto_now_add=True, verbose_name='输入时间')),
            ],
            options={
                'verbose_name': '响应内容',
                'verbose_name_plural': '响应内容',
                'db_table': 'reply',
            },
        ),
    ]
